# The URL the site will be built for
base_url = "https://a-abhyuday.com"
title = "Abhyuday"
description = "Website"
default_language = "en"
generate_sitemap = true
generate_robots_txt = true
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "apollo"
taxonomies = [{ name = "tags"}]
[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"
error_on_missing_language = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]
theme = 'auto'
socials = [
    { name = "linkedin", url = "https://in.linkedin.com/in/annepu-abhyuday", icon = "linkedin"},
    { name = "github", url = "https://github.com/Ann-Abhyuday", icon = "github" },
]
menu = [
    { name = "/home", url = "/", weight = 1 },
    { name = "/posts", url = "/posts", weight = 2 },
    { name = "/projects", url = "/projects", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]
# Put all your custom variables here
#favicon = "rust.png"
fancy_code = true
dynamic_note = true
mathjax = true
mathjax_dollar_inline_enable = true
comment = true
#stylesheets = ["custom.css",]

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

[extra.analytics]
enabled = false
